apiVersion: v1
kind: Service
metadata:
    name: "aspnet-6463"
    labels:
        app: "aspnet-6463"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aspnet-6463"